# Generated by Django 5.0.3 on 2024-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='c_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cus_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_password',
            field=models.CharField(max_length=100),
        ),
    ]
