# Generated by Django 5.0.3 on 2024-04-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0002_alter_company_c_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='c_password',
            field=models.CharField(max_length=200),
        ),
    ]
