# Generated by Django 5.0.3 on 2024-04-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0003_alter_company_c_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cus_password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_password',
            field=models.CharField(max_length=200),
        ),
    ]
