# Generated by Django 5.0.3 on 2024-04-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0004_alter_customers_cus_password_and_more'),
        ('all', '0004_employee_department'),
    ]

    operations = [
    ]
