# Generated by Django 5.0.1 on 2024-04-20 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0006_transaction_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='c_id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='all.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='c_id',
            field=models.ForeignKey(default='a_1', on_delete=django.db.models.deletion.CASCADE, to='all.company'),
            preserve_default=False,
        ),
    ]
