# Generated by Django 5.0.1 on 2024-04-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0007_store_c_id_warehouse_c_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='c_id',
        ),
    ]
