# Generated by Django 5.0.1 on 2024-04-20 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0008_remove_store_c_id_remove_warehouse_c_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='c_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='b_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='b_id',
            new_name='branch',
        ),
    ]
