# Generated by Django 5.0.3 on 2024-04-25 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0009_rename_c_id_branch_company_rename_b_id_store_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='s_admin_id',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='w_admin_id',
        ),
    ]
