# Generated by Django 5.0.1 on 2024-04-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('c_phone', models.IntegerField()),
                ('c_address', models.CharField(max_length=200)),
                ('c_email', models.CharField(max_length=30)),
                ('c_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cus_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cus_name', models.CharField(max_length=30)),
                ('cus_join_date', models.DateField()),
                ('cus_points', models.IntegerField()),
                ('dob', models.DateField()),
                ('cus_phone_no', models.IntegerField()),
                ('cus_email', models.CharField(max_length=30)),
                ('cus_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('b_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('b_address', models.CharField(max_length=200)),
                ('b_phone_no', models.IntegerField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=40)),
                ('emp_phone_no', models.IntegerField()),
                ('dob', models.DateField()),
                ('salary', models.IntegerField()),
                ('emp_email', models.CharField(max_length=30)),
                ('emp_password', models.CharField(max_length=30)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('s_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('s_admin_id', models.CharField(max_length=5, null=True)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.branch')),
            ],
        ),
        migrations.CreateModel(
            name='S_Products',
            fields=[
                ('p_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30)),
                ('p_manufacturer', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('mfg_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.store')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('t_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('date_of_transaction', models.DateField()),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.customers')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('o_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.s_products')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('w_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('w_admin_id', models.CharField(max_length=5, null=True)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.branch')),
            ],
        ),
        migrations.CreateModel(
            name='W_Products',
            fields=[
                ('p_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30)),
                ('p_manufacturer', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('mfg_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('w_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.warehouse')),
            ],
        ),
    ]
